### ISSUE TITLE
How could I flash Heads using 1vyrain?

### ISSUE THREAD

**Issue by h4xor666** [osresearch/heads#1049]
Hey there folks, great work on this project! Big fan. Quick question though - I have built both the t430-flash and the normal t430 roms for my T430 successfully. Unfortunately, this T430 is in pretty bad shape already, and I'm worried that if I take it apart to physically flash it, components will break.

So, my question is, is it possible to just Heads using the option in 1vyrain to flash an alternate BIOS (e.g. Skulls, etc.)? If so, how would I do it? Would I flash the 4MB t430-flash file and then flash the 8MB file like normal? Or would I have to cat them together or something? I am a dumb person, pls don't be mad at me haha I just don't wanna brick my laptop again.

**Comment by tlaurion** [comment]
@h4xor666 you can read https://github.com/osresearch/heads/pull/1015#issuecomment-954977109

t430-hotp-verification was added in #1015 and is now building with fixes that were needed to be able to use gui-init boot path without FBWhiptail.

You should still be ready to reflash externally in case of brick. I have not tested 1vyrain myself.

But flashing t430-flash from 1vyrain, then t430-hotp-verification (if you have a HOTP supporting device like Librem Key or Nitroeky Storage or Nitrokey Pro2, this _should_ work. Note that flashing t430 is to be chosen if not having a HOTP supported USB Security dongle.)

**Comment by h4xor666** [comment]
So I should, with that PR, do make BOARD=t430-flash, flash that with 1vyrain, and then do make BOARD=t430 (I don't have an HOTP supportinf device) and flash that from the t430-flash? Just want to clarify, I'm not fully understanding.

**Comment by tlaurion** [comment]
Exaxtly, while waiting for someone having an external reprogrammer to confirm it is working, which is asked under #1015 namely from Nitrokey people let it be @nitrokey-simon @jan23 or others define under main pinned issue for collaborators and board owners. X230 and T430 are really similar but not the same. My take here is best effort, not owning a t430.

**Comment by h4xor666** [comment]
Gotcha. I have an external programmer, so I can try it out tonight.

**Comment by tlaurion** [comment]
I keep repeating myself in all opening tickets where all is under #1015 but drooped documentation. By flashing through 1vyrain, you would loose 3.5 mb of bios space, reducing your experience to what I call legacy boards. If you backup your two SPI flash and go x230-hotp-maximized instead of flashing x230-flash through 1vyrain, and them from there x230, you could flash x230-maximized board artifacts, both being bottom.ROM and top.ROM images and install Q4.1 from there. Please read #1045 and question documentation needs from there.

1vyrain is made to deactivate, not neuter, ME. It cannot and won't unlock IFD nor take advantage of ME neutered space.

If you have an external reprogrammer, you should flash the maximized ROMs produced for you board. If you use WiFi and QuebesOS 4.1 you will get randomized Mac address by default. Concern is if you use Ethernet and them randomize your Mac address yourself from OS. Let it be Qubesos 4.0 or any other OS to protect your privacy while having a fully open source firmware. Outside if that that us your choice.

**Comment by tlaurion** [comment]
@h4xor666 please comment/review https://github.com/osresearch/heads-wiki/pull/82/files?short_path=529f311#diff-529f311e8716c83389f3e386ff6b8e9a90113d07f137321554820739e2a7b81c

**Comment by tlaurion** [comment]
@h4xor666 : success?

Have you gone the 1vyrain to t430-flash to t430 or you went the t430-maximized externally flashing?

Test reports are important! Thanks!

**Comment by tlaurion** [comment]
And your report from 1vyrain to t430-flash to t430 internal flash would also be more then welcome.

**Comment by h4xor666** [comment]
> And your report from 1vyrain to t430-flash to t430 internal flash would also be more then welcome.

Sorry - I ended up not using Heads. All the best to you.
