### ISSUE TITLE
Thinkpad W530, MAKE BOARD (FULL ORDERED BUILD LOGS HERE UNTIL JOB FAILED)

### ISSUE THREAD

**Issue by Stomatic** [osresearch/heads#1325]
Hi, I would like to install heads for the first time and I was thinking of doing it on a Thinkpad w530, when I go to circleci, in steps, in the "MAKE BOARD" section it says "(FULL ORDERED BUILD LOGS HERE UNTIL JOB FAILED)".
Can I proceed by downloading the necessary files or could there be problems given by the failed job?
Wanting the video card initialized (to use external monitor), I just need to flash the 2 chips after downloading the 2 .rom files (besides configuring through the gui heads), or do I have to do other things?
Thank you.

**Comment by tlaurion** [comment]
>Hi, I would like to install heads for the first time and I was thinking of doing it on a Thinkpad w530, when I go to circleci, in steps, in the "MAKE BOARD" section it says "(FULL ORDERED BUILD LOGS HERE UNTIL JOB FAILED)".
Can I proceed by downloading the necessary files or could there be problems given by the failed job?

@Stomatic Sorry about the confusion. A build for a board is successful or fails. That steps just contains all the logs until failing in order of logs produced. If the build failed, that step would still succeed, but the next one would fail.

Example of a failed pipeline https://app.circleci.com/pipelines/github/tlaurion/heads/1517/workflows/3c2c8504-2900-4a7b-b7b6-9242aa78aecf where talos II board failed its job: https://app.circleci.com/pipelines/github/tlaurion/heads/1517/workflows/3c2c8504-2900-4a7b-b7b6-9242aa78aecf/jobs/18015

As you can see there, the step "succeeded" even though going into its details (logs) failed: https://app.circleci.com/pipelines/github/tlaurion/heads/1517/workflows/3c2c8504-2900-4a7b-b7b6-9242aa78aecf/jobs/18015?invite=true#step-103-1488

----
> Wanting the video card initialized (to use external monitor), I just need to flash the 2 chips after downloading the 2 .rom files (besides configuring through the gui heads), or do I have to do other things?
Thank you.

So I guess you want a dpgu variant.
So this is as of today latest successful pipeline: https://app.circleci.com/pipelines/github/osresearch/heads/524/workflows/d13d6a02-1ffa-40ac-b721-e31ff69483d4

So having to select either k1000m or k2000m variant, choosing hotp variant if you have a Nitrokey 1/2 Pro/ Nitrokey Storage/Librem Key. 

---
Would you suggest a different wording? I have put in capital so that people go look there for logs. Your opened issue teels me that I should have chose a different wording.

**Comment by tlaurion** [comment]
Here is an example of a failed build https://app.circleci.com/pipelines/github/tlaurion/heads/1517/workflows/3c2c8504-2900-4a7b-b7b6-9242aa78aecf/jobs/18015
