### ISSUE TITLE
USB modules should be measured

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#16]
The Linux kernel bootloader should not have USB enabled; loading the modules should require measurement and adjustment of the PCRs (to invalidate the disk encryption keys).

**Comment by osresearch** [comment]
Splitting the USB system into a module increased the size of the initrd by 2 MB. That won't work, unless we're much choosier about which modules to include.

**Comment by jonathanfemideer** [comment]
At the moment, the installation instructions expect the user to flash Heads to the motherboard, and then to boot heads, mount a USB drive, and install Qubes from that drive.

> The Linux kernel bootloader should not have USB enabled

Perhaps I am misunderstanding, but how would the user install Qubes if Heads does not have USB enabled?

**Comment by tlaurion** [comment]
The point made here is to have usb kernel support as module versus built-in
in the kernel. As a module, it is loaded only if required and requested by
the user (u key at prompt) instead of being there by default when the Linux
payload starts.

I'm pretty sure that issue is fixed now, since the modules to be loaded by
the scripts depends of the configuration of the board and its Linux
configuration.

Either way, USB support is there as we speak as modules. This issue should
be closed. Space constraints have been dealt with since 2016.



Le mer. 1 mars 2017 17:06, Jonathan Femideer <notifications@github.com> a
écrit :
