### ISSUE TITLE
Ensure that kernel updates force signing of image

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#223]
https://github.com/osresearch/heads/pull/200#issuecomment-315801765

> There's a few ways to that default boot can fail but leave you available to select an alternate kernel AND have the key accessible. The primary use case is when there's a kernel upgrade and you just want to reset the default and boot right away. Maybe it's safer thought to be in recovery mode for the resign and then require reboot for TPM key unseal.

A kernel update should definitely require a recovery mode resign/reseal.  That might indicate a successful attack that has managed to modify the `/boot` filesystem to gain persistence.

**Comment by flammit** [comment]
Absolutely.  Right now it does require a resign of the updated kernel parameters, but not a reseal of the disk key (which is the old behavior in qubes-init - just needed to do `qubes-update` to update the `boot.hashes`).

I wanted to try to allow the user to resign and immediately boot (including unsealing the TPM key) all without touching the recovery shell.  That doesn't actually work right now because TPM 5 is extended in the signing process and the subsequent TPM unseal operation will fail.

As you said, it's safer in this case to die and go to recovery to manually run `kexec-save-default` or some other means to assert the altered boot config is good.  Maybe in the future if we can trigger a reboot, the user can resign in the menu (after TPM 4 is extended) and reboot to continue in normal mode.
