### ISSUE TITLE
Evaluate Nuklear for creating graphical menus

### ISSUE THREAD

**Issue by paulmenzel** [osresearch/heads#413]
Merge/pull requests #321 [1] and #322 [2] added support for Whiptail to have menus in Bash scripts. To have more graphical pleasing dialogs, [Nuklear][3] should be evaluate. The proof-of-concept payload [CBUI is under review][4].

[1]: https://github.com/osresearch/heads/pull/321
[2]: https://github.com/osresearch/heads/pull/322
[3]: https://github.com/vurtun/nuklear
[4]: https://review.coreboot.org/#/c/coreboot/+/23586/

**Comment by tlaurion** [comment]
@paulmenzel : Can you say a couple of words on the advantages over whiptail?

**Comment by tlaurion** [comment]
@paulmenzel : beautiful.
@kakaroto : opinions?

**Comment by kylerankin** [comment]
Nuklear certain looks very pretty and has a lot of features, but I think there are a few advantages to our current whiptail/fbwhiptail solution:

- Since fbwhiptail syntax is compatible with whiptail syntax, you can use fbwhiptail opportunistically on machines that support the framebuffer within Heads and on machines that don't, easily fall back to whiptail without having to write two separate programs, one for a framebuffer GUI and one for a console-based one.
- whiptail's bash-based syntax is simpler and a lot more accessible for contributors to take and customize for their own needs compared to building a program in C and use system calls to perform functions. 
- As we continue to build GUI menus for Heads we will want to pick a solution and stick with it, as the further along we go, the more rewriting we'll have to do if we switch tools wholesale.

**Comment by tlaurion** [comment]
Not so related @paulmenzel : what graphical menus would exist in go? ( For u-root / systemboot / linuxboot ? )

**Comment by tlaurion** [comment]
whiptail it is.
