### ISSUE TITLE
GPG cards working with Heads

### ISSUE THREAD

**Issue by sam3729** [osresearch/heads#586]
Which GPG cards are compatible with Heads ?
The wiki always talk about Yubikey but I've seen on mailing lists that Nitrokey and Libremkey also work.
Do you know if Trezor works or should work with Heads ?
Trezor supports GPG : https://wiki.trezor.io/GPG
I'm new to Heads. I've just installed it on a x230 and I'd like to buy a GPG card but I don't know yet which one.
Thanks for the nice work !

**Comment by tlaurion** [comment]
@sam3729 

For Heads compliance, any gpg card supported by gpg should do. Dont know if Trezor would work out of the box but I don't see why not. You will have to import your GPG public key into the rom, and you'd be good to go.

If you want HOTP sealing, so that the GPG card reports visually with its LED flashing green if firmware integrity is attested or red otherwise, then currently only Librem Key, NitroKey Pro v2 and NitroKey Storage v2 are implementing HOTP. Note that for that feature to be present under Heads, CONFIG_LIBREMKEY needs to be defined under board configuration.


_Sent from my Galaxy S3 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_
