### ISSUE TITLE
Yubikey

### ISSUE THREAD

**Issue by alelopezperez** [osresearch/heads#629]
Hi!
Am Following the Heads Installation Guide (http://osresearch.net/Installing-Heads) and i see there is a need to use the yubikey to store private keys. is it posible to use and plain USB to store the private keys and how do i proceed to use the guide with a plain USB instead of a Yubikey

**Comment by RamonRomeroQro** [comment]
._.xD

**Comment by tlaurion** [comment]
@alelopezperez : Please review [keys entry](https://github.com/osresearch/heads-wiki/blob/master/Keys.md#owners-gpg-key).

The idea with using a USB security token (HOTP compliant or not for remote attestation is another subject) is a requirement of the Heads project. The USB security token (aka GPG smartcard) is to sign /boot files integrity with your private key, inside of that external smartcard, so that your public key, inside of Heads ROM, is used to verify files integrity internally without the need of the USB security token. To serve that purpose, Yubikey, Nitrokey basic/pro/storage, Librem Key can be used to serve the purpose of GPG smartcard.

Then, if you can to use a HOTP enabled security token so that firmware integrity measurements takn by the TPM are sealed inside of an external smartcard (remote attestation), your choices are reduced to Librem Key/Nitrokey Pro/Nitrokey Storage.

The vocabulory is under review and will change to something like:
- GPG smartcard (To serve signing/validation)
- HOTP enabled security token (GPG Smartcard + remote attestation)

If you have any comment/improvement/discussion to open, please go forward!
