### ISSUE TITLE
xx20-maximized boards SPI already full when adding cryptsetup2

### ISSUE THREAD

**Issue by tlaurion** [osresearch/heads#926]
[xx20-maximized boards fail to include cryptsetup2](https://app.circleci.com/pipelines/github/tlaurion/heads/646/workflows/b896c1ed-485d-4006-bc81-72ee72d8ae1a/jobs/694) in their current board configuration (which includes NKSTORECLI, E1000E, DROPBEAR, while excluding HOTPas their xx30-hotp-counterpart).

xx20-maximized board configs were direct duplicate of xx30-boards which have 3.5mb additional SPI space  (11.5mb) compared to xx20 boards who have a total usable SPI space of 7.5mb maximum.

The xx20 boards included NKSTORECLI by default, where there is actually no use case defined for those boards as of right now.
The end goal of this module inclusion is envisioned mainly at reownership, so that the Nitrokey Storage encrypted storage is used to provision reownership secrets then reuse secrets all along of the reownership wizard across reboots (The USB Security dongle kept powered on an unlocked until power off), which is not planned by anybody else then Insurgo who paid for the implementation AFAIK, and no code takes advantage of it as of right now.

Other low hanging fruits possibilities to squeeze required space are unused modules as of right now: E1000E and DROPBEAR inclusion in rom, that could be removed without consequence.

@Thrilleratplay : Opinion welcome.

**Comment by Thrilleratplay** [comment]
@tlaurion This is going to be an on going issue.  I have no suggestions on what to keep or what to take out.  What ever is decided, there will be someone asking for another configuration.  Whatever you decide to add or remove for the CI build is fine with me but if possible would prefer, at some, we create a chart of features and the required space to allow the user to build the version that best suits them.

**Comment by fhvyhjriur** [comment]
From the OpenWrt project for devices with 4mb SPI chips the space also got low with growing linux kernel and maybe it helps to know how its done there:
The default image that can be installed without any compilation and that is kept updated for security and other updates is the one that probably most user would be happy with. There is no real discussion with the users about what most user would probably like to have. The developer decide the default usability on their own.
There should be one default and ready image available for download and all user with different wishes have to build their own image.
Example in OpenWrt for custom user-wishes: Users that want to have VPN functionality instead of the Webbrowser-GUI. Other users swap out their SPI chips for more space or solder USB wires to some legs of a chip to have a USB-port and then also need custom images they build with small changes to the already existing default image-configuration.

**Comment by tlaurion** [comment]
@fhvyhjriur agreed, while board additions are welcome from the community users, where board names should be clear enough to state what the use is. For example, if a SPI change is required, the board name should explicit that with `-16mb_SPI`, and where users pushing those boards should also be the maintainers of such boards. The direction that will be pushed forward is that if a board cannot be built anymore for space limitation, that board will need to be removed from CI for other boards to continue to be built and an issue will be opened, stating the last commit ID with which it built with its current subset of functionalities. 

This issue is fixed with #928, which removes NITROCLI, while being ready for CRYPTSETUP2 change which will be needed for #237 enforcing LUKS2 at installation.
